---
- name: Michael Goertemoeller
  color: "#00ff00"
  id: '3318241602'
  distance: 0.0
  time: '3:12:58'
  timeSeconds: 11578
  routeName: 3318241602.geojson
  timingData: 3318241602-timing.json
- name: James O
  color: "#ff4400"
  id: '3318436209'
  distance: 0.0
  time: '3:18:54'
  timeSeconds: 11934
  routeName: 3318436209.geojson
  timingData: 3318436209-timing.json
- name: Lyle Dailey
  color: "#ffcc00"
  id: '3318333455'
  distance: 0.0
  time: '3:39:21'
  timeSeconds: 13161
  routeName: 3318333455.geojson
  timingData: 3318333455-timing.json
- name: Michael Chewning
  color: "#ff00cc"
  id: '3323832037'
  distance: 0.0
  time: '3:51:17'
  timeSeconds: 13877
  routeName: 3323832037.geojson
  timingData: 3323832037-timing.json
- name: Davis Griffin
  color: "#0088ff"
  id: '3323082807'
  distance: 0.0
  time: '4:37:31'
  timeSeconds: 16651
  routeName: 3323082807.geojson
  timingData: 3323082807-timing.json
