- name: Evan
  routeName: CoronaCat.geojson
  color: "#de2c6e"
  id: evan
  distance: 18.79
  time: "58:34"
  timingData: CoronacatEvan_normalized.json

- name: Hannah
  routeName: Coronacat_race_.geojson
  color: "#86630f"
  id: hannah
  time: "1:03:04"
  distance: 19.39
  timingData: CoronacatHannah_normalized.json

- name: Michael
  routeName: Corona_Cat.geojson
  color: "#600223"
  id: michael
  time: "1:07:58"
  distance: 19.51
  timingData: CoronacatMicheal_normalized.json

- name: Vincent
  routeName: CoronaCatVinccent.geojson
  color: "#342d8c"
  id: vincent
  time: "1:08:04"
  distance: 19.17
  timingData: CoronacatVincent_normalized.json

- name: Jesse
  routeName: CORONACAT_Alleycat_2020.geojson
  color: "#039c3c"
  id: jesse
  time: "1:10:48"
  distance: 18.85
  timingData: CoronacatJesse_normalized.json

- name: Tanner
  routeName: CoronaCat.geojson
  color: "#5539ec"
  id: tanzi
  time: "1:14:53"
  distance: 19.84
  timingData: CoronacatTanner_normalized.json

- name: Ders
  routeName: CoronacatAndreas.geojson
  color: "#ec3939"
  id: ders
  time: "1:22:32"
  distance: 21.64
  timingData: CoronacatAndreas_normalized.json

- name: Daniel
  routeName: Alleycat_Covid_19_Coronacat.geojson
  color: "#8427cd"
  id: daniel
  distance: 19.27
  time: "1:33:21"
  timingData: CoronacatDaniel_normalized.json

- name: Charlotte
  routeName: Charlotte.geojson
  color: "#2ba8f5"
  id: charlotte
  distance: 23.74
  time: "1:37:14"
  timingData: CoronacatCharlotte_normalized.json

- name: Brian (Organizer)
  routeName: Brian.geojson
  color: "#e3f700"
  id: brian
  distance: 18.89
  time: "1:14:36"
  timingData: CoronacatBrian_normalized.json
